### ISSUE TITLE
keyboard not set to locale

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-iso#100]
if i choose german language  on bootscreen (Bios System) i get german lang on Live-Environment but keyboard setting is still US-English:
[locale-keyboard-setings](https://i.imgur.com/ItI6eNR.png)
later if i go to start cnchi it canges, but if i want to use without installation (rescue e.t.c.) i need to add german keyboard and set it by hand...

**Comment by karasu** [comment]
Official iso?

**Comment by killajoe** [comment]
Yes! Also after installation into the new system if it is Gnome..

**Comment by killajoe** [comment]
I found the error: setting keyboard to german, needs to choose a variant too, if you so not do it falls back to US-default keyboard...
