### ISSUE TITLE
issue building iso from testing branch

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-iso#103]
`==> dkms install zfs/0.7.6 -k 4.15.3-2-ARCH
configure: error: 
	*** Please make sure the kmod spl devel <kernel> package for your
	*** distribution is installed then try again.  If that fails you
	*** can specify the location of the spl objects with the
	*** '--with-spl-obj=PATH' option.  Failed to find spl_config.h in
	*** any of the following:
	/usr/src/spl-0.7.6/4.15.3-2-ARCH
	/usr/src/spl-0.7.6
^[Error!  Build of zavl.ko failed for: 4.15.3-2-ARCH (x86_64)
Consult the make.log in the build directory
/var/lib/dkms/zfs/0.7.6/build/ for more information.
`

**Comment by killajoe** [comment]
but seems that building went true this error, i will see if it works ;)
As i am not happy with my try ou to build antergos_:rescue iso from scratch with pure archiso, i want to go back to antergos-iso, so i try to build firstly as it is shipped here, if it works i will provide antergos-iso-testing releases on my webspace too.

**Comment by killajoe** [comment]
`>>> Updating module dependencies. Please wait ...
Error! Could not find module source directory.
Directory: /usr/src/spl-0.7.6-1 does not exist.`

**Comment by karasu** [comment]
@killajoe 

It's been some time since I tried the testing branch. The quickest way to bypass this is to change your config file and disable zfs. If you want/need zfs to be enabled, you will have to fix this or wait until I fix it myself... 😬

**Comment by killajoe** [comment]
I do not need ZFS, and i do not like it, as it is hard to integrate and caus of this unstable on using it...
Indeed i can build fine without zfs and integration for nvidia drivers works fine!
I will try to make use of this for antergos rescue ISO too! 
You already have done a lot at testing ISO! thats awesome!!!

**Comment by killajoe** [comment]
My first build with nvidia is here: http://kamprad.net/Downloads/Antergos-Nvidia-ISO/
