### ISSUE TITLE
zd1211-firmware not in repo

### ISSUE THREAD

**Issue by searedvandal** [Antergos/antergos-iso#110]
zd1211-firmware is not in the repos, so building the ISO with this package in the packages.both list makes the build fail. Should this be removed from the package list for the ISO or does it need to be included in the repo again? I understand it was part of the repo previously?

**Comment by killajoe** [comment]
zd1211-firmware 1.5-2 has been removed from the [core] repository.
https://www.archlinux.org/packages/core/any/zd1211-firmware/

https://sourceforge.net/p/zd1211/activity/?page=0&limit=100#535fb2bb34309d4520dc6730

looks like way old and unmaintained maybe useless also?

**Comment by searedvandal** [comment]
Yeah, probably. So I guess it should be removed from the packages.both list if it's not needed anymore?

**Comment by searedvandal** [comment]
I see package has been removed from package list, so closing this.
