### ISSUE TITLE
multilib commented out in pacman.conf?

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-iso#115]
https://forum.antergos.com/topic/10591/metalinks-installation-error

**Comment by karasu** [comment]
@killajoe In which iso?

**Comment by CurtisBelt** [comment]
@karasu The "Live" version for sure -- haven't used the minimal one before. Latest version 18.9. Many are using 18.8 for now.

**Comment by killajoe** [comment]
![bildschirmfoto vom 2018-09-09 00-25-53](https://user-images.githubusercontent.com/16797647/45259191-f29be680-b3c6-11e8-8254-96c298918a5d.png)

**Comment by karasu** [comment]
I'll check it out tomorrow. Thanks!

**Comment by killajoe** [comment]
Very nice Mr. @ karasu, take the time you need!

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-iso/commit/fedbc3c1f89e8206c45b68386be0f147966e9a19
Totally my fault.
