### ISSUE TITLE
Include Broadcom drivers in the live system

### ISSUE THREAD

**Issue by lots0logs** [Antergos/antergos-iso#17]
From #16

**Comment by RavanH** [comment]
yes please...

**Comment by lots0logs** [comment]
This is actually already done in the latest testing images. Have you tried them? Let me know if its not working. Thanks!

**Comment by RavanH** [comment]
Hi, just downloaded the DVD version from http://build.antergos.com/browse/testing (is that the one?) but it does not seem to load drivers for the wifi card.

"lspci -k" tells me:
`
Network controller: Broadcom Corporation BCM4318 (Airforce One 54g) 802.11g Wireless LAN Controller (rev 02)
Subsystem: Hewlett-Packard Company Broadcom 802.11b/g WLAN
Kernel modules: ssb, wl
`

**Comment by lots0logs** [comment]
Thanks for the info. It appears I forgot to add the package to the iso after I added it to our repo :sweat_smile:  It will be in the next build.

**Comment by RavanH** [comment]
Let me know when it's ready and I'll be happy to test it :-)

**Comment by ErikPartridge** [comment]
Still causing problems with the broadband drivers, preventing install on my machine here.
