### ISSUE TITLE
Failed to open file EFI\archiso\intel_ucode.img

### ISSUE THREAD

**Issue by ApertureAndroid** [Antergos/antergos-iso#19]
When booting a live USB using any of the testing ISOs and select Antergos x86_64 UEFI USB, I get.
"Failed to open file EFI\archiso\intel_ucode.img
Trying to load files to higher address
Failed to open file EFI\archiso\intel_ucode.img"

Copying intel_ucode.img from \arch\boot\ inside the USB to EFI\archiso\ lets the USB boot normally.

**Comment by hugo19941994** [comment]
Same thing happened when installing Antergos in a Surface Pro 1.

**Comment by LucaFraga** [comment]
Same on acer e5-571g when booting an usb with UEFI.

**Comment by noderat** [comment]
Confirmed with Dell XPS 8700. It also causes this ISO to black screen on boot.

**Comment by mirh** [comment]
Uh, for the records, [this](https://bbs.archlinux.org/viewtopic.php?id=199871) is prolly the cause.
