### ISSUE TITLE
memtest86+ test #7 false positives (random number sequence error)

### ISSUE THREAD

**Issue by jorenlove** [Antergos/antergos-iso#20]
Hope this is the right place for this. I ran memtest from the 2015.01.11 iso on 3 different machines (one being a VirtualBox VM) and got bitten by this bug: 
https://bugs.launchpad.net/ubuntu/+source/memtest86+/+bug/1071209

**Comment by ShapeShifter499** [comment]
Why man, just why?      I never knew this bug existed until I tested today on 2 other machines that work fine.   I got rid of a netbook over this bug thinking it was no longer good (it has on board ram that is soldered in)

**Comment by jorenlove** [comment]
Sucks for sure, was this on a recent build of the ISO? I looked around months ago but I couldn't figure out how memtest was getting into the build. Maybe I'll have another look this week
