### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by prescott66** [Antergos/antergos-iso#21]
I have selected slovak language at boot, but Cnchi is always in english, notifications with cnchi updating too.
Default keyboard in Cnchi is english and they should be slovak too.

**Comment by karasu** [comment]
I'll check the translations, if nobody has translated Cnchi to Slovak you'll see it in English as default.
Can't you select Slovak in the language page?

**Comment by prescott66** [comment]
I have translated it :-)

**Comment by prescott66** [comment]
I can select it but all is in english, keyboard too...

**Comment by lots0logs** [comment]
@prescott66 How recently did you submit translations? They may not be in the package yet. I will check on it asap.

**Comment by prescott66** [comment]
Check it on transifex.cnchi is mostly translated by me.

**Comment by prescott66** [comment]
https://www.transifex.com/projects/p/antergos/language/sk/

**Comment by lots0logs** [comment]
Thanks I see that. Translations are not immediately packaged. We package them about once a month. BTW, Thanks for contributing to the translations!
