### ISSUE TITLE
[Suggestion] Add 'powerpill'

### ISSUE THREAD

**Issue by frozenxuan** [Antergos/antergos-iso#36]
Please add 'powerpill' to ensure fastest download speed during installation.

**Comment by karasu** [comment]
Do you mean to our installer? It's not using pacman to download packages.

And some time ago I did some tests using aria2c (that is what powerpill uses) and I saw a lot of memory usage with no real speed benefit. Maybe for slow connections is different, but here it didn't make a difference.

At this moment the installer uses the requests library (that internally uses urllib).
