### ISSUE TITLE
Muted volume after each login (XFCE)

### ISSUE THREAD

**Issue by prescott66** [Antergos/antergos-iso#37]
After each boot of XFCE desktop, is volume of main channel muted.
i have googled this bug report: https://bugzilla.xfce.org/show_bug.cgi?id=5091
which says, that it is not XFCE related. I have tried command "alsactl store", but issues stays anyway.
Maybe it is Antergos related.

Please give me some instructions, how to debug this issue. It is very annoing.

**Comment by lots0logs** [comment]
This is not the proper place for troubleshooting the issue you are experiencing. Please post over on our forum. Thanks.
