### ISSUE TITLE
[Minimal] Fails to detect USB wifi dongle (works in full ISO)

### ISSUE THREAD

**Issue by karasu** [Antergos/antergos-iso#43]
I downloaded latest minimal 32bit iso for installation. but it failed to detect my USB dongle device. so i cant create data connection. however this is not the same with live iso. it works fine and and detect my usb modem. please fix it for minimal iso.

https://forum.antergos.com/topic/3350/minimal-iso-doesnt-detect-usb-mobile-broadband-internet

**Comment by lots0logs** [comment]
The minimal ISO only includes the most common kernel modules in an effort to keep the filesize of the ISO as small as possible. For cases where the user needs uncommon drivers they should use the Live ISO.

**Comment by karasu** [comment]
Seems fair to me. I'd just filled the issue in case the driver was already in the iso but something was wrong.
Thanks!
