### ISSUE TITLE
ntpd service is not enabled

### ISSUE THREAD

**Issue by karasu** [Antergos/antergos-iso#49]
ntpd service is not enabled, time is wrong and then pacman fails in some circumstances.

`sudo systemctl enable ntpd` fixes it.

**Comment by Mikaela** [comment]
What is wrong with systemd-timesyncd? `sudo timedatectl set-ntp true`

**Comment by lots0logs** [comment]
@karasu This was working fine last time I checked. Maybe its a systemd bug? I will look into it.

**Comment by karasu** [comment]
@Mikaela Nothing. I keep forgeting about it, that's it. 

@lots0logs : Tested with the latest iso. Let me check systemd-timesyncd as @Mikaela suggests, though.

**Comment by stratus-ss** [comment]
This is still an issue for the latest iso (02-21-2016). NTP service is **Active: inactive (dead)**

timedatectl shows that the service is disabled


```[root@ant-16 antergos]# systemctl status ntpd
● ntpd.service - Network Time Service
   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; disabled; vendor preset
   Active: inactive (dead)

[root@ant-16 antergos]# timedatectl
      Local time: Mon 2016-03-14 09:23:15 EDT
  Universal time: Mon 2016-03-14 13:23:15 UTC
        RTC time: Mon 2016-03-14 13:23:16
       Time zone: America/Toronto (EDT, -0400)
 Network time on: no
NTP synchronized: no
 RTC in local TZ: no
[root@ant-16 antergos]# systemctl status ntpd
● ntpd.service - Network Time Service
   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; disabled; vendor preset
   Active: inactive (dead)

```

**Comment by karasu** [comment]
@stratus-ss : in new installs, cnchi uses systemd-timesync. In our live iso I can't remember if this has been fixed or not...
