### ISSUE TITLE
Antergos ISO 3/20 does not work with dd in UEFI systems

### ISSUE THREAD

**Issue by karasu** [Antergos/antergos-iso#52]
If you format the drive as FAT32, then copy the files to it and set it bootable it works fine

**Comment by Mikaela** [comment]
And only UEFI supports booting from FAT32 when the files have been copied so if this also affects BIOS, that workaround is unavailable.

**Comment by lots0logs** [comment]
@karasu Have you been able to confirm this using actual hardware?

**Comment by karasu** [comment]
@lots0logs No, but now I have a UEFI laptop, so we will be able to test this things, finally. :grimacing: 

Will test and post my findings here (by the way, previous ISO worked if you selected the CD/DVD option, even if I was using a USB. The other options didn't work at all).

Maybe there's something different with this iso? Will test asap.

**Comment by lots0logs** [comment]
@karasu Cool..I actually have actual hardware to test on now. But apparently I misplaced my damn usb stick because I couldn't find it at the time I first replied to this issue (and I still can't :unamused: )

**Comment by Mikaela** [comment]
This is another FAQ at IRC, any status update?
