### ISSUE TITLE
Default GTK Theme bad working on minimal-iso

### ISSUE THREAD

**Issue by varlesh** [Antergos/antergos-iso#53]
If use default GTK theme bad working and some options not visible on Cnchi.
Release: antergos-minimal-2016.03.20-x86_64.iso
For example,
Select Location:
![screenshot from 2016-04-01 16-54-41](https://cloud.githubusercontent.com/assets/8083855/14214300/0385de82-f845-11e5-87df-f4c83abf509f.png)
Hard drive settings (More item not visible)
![screenshot from 2016-04-01 16-55-37](https://cloud.githubusercontent.com/assets/8083855/14214299/03829a74-f845-11e5-9979-53d7185cc4c2.png)
This solved if delete GTK config and use Adwaita GTK Theme, and run Installer again:
```
rm -rf ~/.gtk*
rm -rf ~/.config/gtk*
```

**Comment by karasu** [comment]
I guess this is because of a GTK update that always breaks themes.
When Numix-Frost is updated this will go.
