### ISSUE TITLE
Having pamac in live gives problems to pacman (db.lck blocking pacman db)

### ISSUE THREAD

**Issue by karasu** [Antergos/antergos-iso#54]
Having pamac in live gives problems to pacman (db.lck being blocked)

I think we should remove pamac from live ISO (or at least disable it).

**Comment by lots0logs** [comment]
Last I checked it is disabled..you can see in the build script that we are running `systemctl disable pamac` :confused:

**Comment by karasu** [comment]
I just checked and db.lck was on, so I assumed it was pamac's fault. Let me recheck.

**Comment by karasu** [comment]
Yep, it's running by default :cry:

**Comment by lots0logs** [comment]
We're also running pacman to check for cnchi updates. I will edit the pacman-boot script and kill pamac before starting cnchi. After all, situations like this are the reason I implemented the pacman-boot script in the first place (make changes without rebuilding ISOs) :grinning:

**Comment by karasu** [comment]
:+1:

**Comment by lots0logs** [comment]
done.

**Comment by karasu** [comment]
Oh, do you think we should remove pamac from live iso anyway?

**Comment by lots0logs** [comment]
I'm not sure..My only concern with removing it is whether or not people trying the live environment are using it to browse the package repos?

**Comment by karasu** [comment]
tbh I have no idea...

**Comment by Mikaela** [comment]
> I will edit the pacman-boot script and kill pamac before starting cnchi. After all, situations like this are the reason I implemented the pacman-boot script in the first place (make changes without rebuilding ISOs) ￼

Wouldn't it be easier to remove `/etc/xdg/autostart/pamac-tray.desktop` from the iso?
