### ISSUE TITLE
No /etc/ca-certificates/extracted/tls-ca-bundle.pem file

### ISSUE THREAD

**Issue by karasu** [Antergos/antergos-iso#61]
Hi,

I don't know if it is intentional, but each time I try to run a command that needs to check the iso certificates, I get that /etc/ssl/certs/ca-certificates.crt is missing. And it's missing because this is a symlink to /etc/ca-certificates/extracted/tls-ca-bundle.pem file, which is nowhere to be found.

Could it be that something has been removed from the iso? (all ca-certificates packages are installed, though).

**Comment by karasu** [comment]
If I reinstall ca-certificates and ca-certifiactes-utils the issue disappears. There must be something wrong with the ISO, as the packages are already installed but not working.

**Comment by lots0logs** [comment]
Hmm..maybe there was a packaging bug with the version of those packages on the iso. I will apply a hotfix for this in the pacman-boot script to take care of this until the next iso images

**Comment by lots0logs** [comment]
@karasu Done. Let me know if its okay now.

**Comment by UgnilJoZ** [comment]
Probably not really your bug, but Arch's.

I had this issue using Arch Linux. Reinstalling ca-certificates did not, but executing `update-ca-trust` did work fine for me.

**Comment by lots0logs** [comment]
Yeah its an issue with the new alpm hooks not being run inside of chroot when using pacstrap. I havent had a chance to put together all the details necessary for an upstream bug report yet (will try to do it before this weekend is over tho!)
