### ISSUE TITLE
[USABILITY] Numix theme breaks GTK 3.20 interfaces

### ISSUE THREAD

**Issue by GabMus** [Antergos/antergos-iso#66]
The Numix GTK theme breaks the user experience in GTK 3.20 desktop environments (GNOME) and applications.

Consider switching ASAP to another theme, be it adwaita or Arc, but do it quickly: it's been like this for a lot of time and it really breaks the user experience and it's difficult for beginners to figure it out.

**Comment by lots0logs** [comment]
What is it exactly that you are referring to as broken? Numix and Numix Frost were both updated for GTK 3.20 months ago :confused:

**Comment by GabMus** [comment]
Mostly the desktop gets white when enabling desktop icons.

**Comment by Wyn10** [comment]
@GabMus It sounds like you're using an outdated iso.

**Comment by GabMus** [comment]
@Wyn10 I don't think so. This is a fully updated system running antergos: https://gfycat.com/HeavenlyImaginativeBluefintuna

**Comment by lots0logs** [comment]
That appears to be a bug but it certainly does not break everything. I'm closing this as invalid. You can check the theme repo to follow the open bug report for the issue if you like. Cheers!
