### ISSUE TITLE
Cnchi crashes after startup

### ISSUE THREAD

**Issue by pointhi** [Antergos/antergos-iso#71]
Simply when the GUI starts, it says something like not enough privileges to start Cnchi (or something similar). So everyone has to start Cnchi manually using the top bar

**Comment by stratus-ss** [comment]
I wasn't able to reproduce this on my setup. I tested with the following isos:

antergos-2016.09.25-x86_64.iso            
antergos-minimal-2016.09.25-x86_64.iso

Do you have any logs? What setup did you encounter this on?

**Comment by lots0logs** [comment]
This was a bug in the previous ISO release. It has been fixed :smiley:
