### ISSUE TITLE
Issues with 2016.12.27 testing ISO

### ISSUE THREAD

**Issue by philwyettreb** [Antergos/antergos-iso#75]
Test install of 2016.12.27 ISO:

Install inside VM with same config as used for current 2016.11 ISO that is fine.

- Hangs at prompt before going to desktop.
- Missing icons.

![screenshot from 2016-12-30 00-53-52](https://cloud.githubusercontent.com/assets/24805379/21557996/8f1c900a-ce2b-11e6-870c-2a953ebe3228.png)
![screenshot from 2016-12-30 00-54-40](https://cloud.githubusercontent.com/assets/24805379/21557997/8f23d1bc-ce2b-11e6-8d03-ef9e3bbd984b.png)
![screenshot from 2016-12-30 00-55-28](https://cloud.githubusercontent.com/assets/24805379/21557998/8f269ca8-ce2b-11e6-929b-44f88fa9df86.png)
![screenshot from 2016-12-30 00-55-39](https://cloud.githubusercontent.com/assets/24805379/21557999/8f29e9da-ce2b-11e6-9df4-74424f10f036.png)

**Comment by lots0logs** [comment]
Yep, we're aware. That's why there has been no official ISO for december. I was able to track down the cause of the issue yesterday. We'll release an official iso next week. Cheers!
