### ISSUE TITLE
minimal iso, add orca to live image to make it accessible

### ISSUE THREAD

**Issue by mhussaincov** [Antergos/antergos-iso#87]
it would be usefull to me if orca the screen reader created by gnome was added to the live iso.
with out orca, I am not able to use the minimal ISO.
thank you for considdering this.

**Comment by mhussaincov** [comment]
is there any news on this issue?

**Comment by lots0logs** [comment]
Hi,

The minimal iso is intended to provide an absolute minimal environment to run the installer which makes the size of the ISO as small as possible. I'm afraid for Orca support you'll need to use the default ISO. Sorry!
