### ISSUE TITLE
syslinux version in iso should be updated

### ISSUE THREAD

**Issue by TitouanT** [Antergos/antergos-iso#88]
Made a live usb have been only possible for me with rufus on windows because it handle the version issue of syslinux by downloading the missing files.
However if I make the usb on linux with or without GUI, I can't boot.

**Comment by TitouanT** [comment]
did you even try ?

**Comment by lots0logs** [comment]
We use whatever version is in the Arch repos. If its not new enough, I'd recommend reporting it to Arch.
