### ISSUE TITLE
MATE Version, NumLock on by Default

### ISSUE THREAD

**Issue by jlacroix82** [Antergos/antergos-iso#91]
I just installed the MATE version, and I noticed that NumLock is turned on by default. The reason this is bad, is because on laptops, this will cause you (for example) to type 5 when you press the letter I. Toggling NumLock off fixes this.

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-gsettings/commit/38f81fa63a9f8d69b6337d778c7c787c5622e5aa
