### ISSUE TITLE
Login screen wallpaper

### ISSUE THREAD

**Issue by jrock2004** [Antergos/antergos-iso#97]
Not sure if this is the place to put this, but after installing the newest ISO, the login and lock screen has a wallpaper of people. I go into Gnome settings and change lock screen wallpaper. I even go into gnome tweak tools to change it, but the wallpaper remains.

I would think you would use another type of wallpaper then something so personal.

**Comment by jrock2004** [comment]
I see you need to go into lightdm itself to change this. Sorry to bother you

**Comment by lots0logs** [comment]
Actually you change it directly on the login screen (click the button that appears in the top-left corner).
